# Generated by Django 4.1.2 on 2022-11-07 21:21

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dozent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Prof.', 'Prof.'), ('Dr.', 'Dr.')], default='Prof.', max_length=5)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Dozenten',
            },
        ),
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('semester', models.CharField(choices=[('WS', 'Wintersemester'), ('SS', 'Sommersemester')], default='', max_length=3)),
                ('dozent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dozent')),
            ],
            options={
                'verbose_name_plural': 'Kurse',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('TUTOR', 'Tutor'), ('KURSLEITER', 'Kursleiter')], default='ADMIN', max_length=10, verbose_name='Role')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Benutzer',
            },
        ),
        migrations.CreateModel(
            name='Kursleiter',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Kursleiter',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
            managers=[
                ('kursleiter', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Tutoren',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('user.user',),
            managers=[
                ('tutor', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_hours', models.FloatField(default=0)),
                ('anzahl_korrekturen', models.IntegerField(default=0)),
                ('kurs', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.kurs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.tutor')),
            ],
            options={
                'verbose_name_plural': 'Tutoren Profile',
            },
        ),
        migrations.CreateModel(
            name='KursleiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurs_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.kurs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.kursleiter')),
            ],
            options={
                'verbose_name_plural': 'Kursleiter Profile',
            },
        ),
        migrations.AddField(
            model_name='kurs',
            name='kursleiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.kursleiter'),
        ),
    ]
