# Generated by Django 4.1.2 on 2022-11-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dozent',
            old_name='first_name',
            new_name='nachname',
        ),
        migrations.RenameField(
            model_name='dozent',
            old_name='last_name',
            new_name='vorname',
        ),
        migrations.RenameField(
            model_name='kurs',
            old_name='description',
            new_name='beschreibung',
        ),
        migrations.RenameField(
            model_name='tutorprofile',
            old_name='work_hours',
            new_name='arbeitsstunden',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='nachname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='vorname',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TUTOR', 'Tutor'), ('KURSLEITER', 'Kursleiter')], default='ADMIN', max_length=10, verbose_name='Rolle'),
        ),
    ]
