# Generated by Django 4.1.2 on 2022-10-26 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='anzahl_korrekturen',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='kurs',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.module'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='work_hours',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher')], max_length=10, verbose_name='Role'),
        ),
    ]
